Repository brain-tec/mail-addons, pull requests merged in 2019-10, with the labels that each got.

#64 Syncing from upstream it-projects-llc/mail-addons (10.0)
  .travis.yml
Labels: 10.0

#65 Syncing from upstream it-projects-llc/mail-addons (13.0)
  .travis.yml
  mail_all/README.rst
  mail_all/__manifest__.py
  mail_archives/README.rst
  mail_archives/__manifest__.py
  mail_multi_website/README.rst
  mail_multi_website/__manifest__.py
  mail_private/README.rst
  mail_private/__manifest__.py
  mail_sent/README.rst
  mail_sent/__manifest__.py
  mail_to/README.rst
  mail_to/__manifest__.py
Labels: 13.0

#66 Syncing from upstream it-projects-llc/mail-addons (12.0)
  mail_multi_website/README.rst
  mail_multi_website/__manifest__.py
  mail_multi_website/doc/index.rst
  mail_multi_website/static/description/index.html
  mail_private/__manifest__.py
  mail_private/doc/changelog.rst
  mail_private/models.py
  mail_private/static/src/xml/mail_private.xml
Labels: 12.0

#67 Syncing from upstream it-projects-llc/mail-addons (12.0)
  mail_sent/__manifest__.py
  mail_sent/doc/changelog.rst
  mail_sent/i18n/mail_sent.pot
  mail_sent/static/src/js/sent.js
Labels: 12.0

#68 Syncing from upstream it-projects-llc/mail-addons (13.0)
  .travis.yml
  mail_base/models.py
  mail_move_message/mail_move_message_models.py
  mail_multi_website/models/ir_property.py
  mail_multi_website/models/mail_template.py
  mail_multi_website/models/res_users.py
  mail_private/models.py
  mail_sent/models.py
  res_partner_company_messages/models.py
  res_partner_mails_count/models.py
Labels: 13.0

#72 Syncing from upstream it-projects-llc/mail-addons (13.0)
  .github/FUNDING.yml
Labels: 13.0

#73 Syncing from upstream it-projects-llc/mail-addons (11.0)
  .travis.yml
  mail_base/README.rst
  mail_base/__init__.py
  mail_base/__manifest__.py
  mail_base/controllers/main.py
  mail_base/doc/changelog.rst
  mail_base/models.py
  mail_base/static/lib/base.js
  mail_multi_website/README.rst
  mail_multi_website/__manifest__.py
  mail_multi_website/doc/index.rst
  mail_multi_website/static/description/index.html
  mail_private/__init__.py
  mail_private/__manifest__.py
  mail_private/doc/changelog.rst
  mail_private/full_composer_wizard.xml
  mail_private/i18n/mail_private.pot
  mail_private/models.py
  mail_private/static/src/css/mail_private.css
  mail_private/static/src/js/mail_private.js
  mail_private/static/src/xml/mail_private.xml
  mail_private/template.xml
  mail_private/tests/__init__.py
  mail_private/tests/test_js.py
  mail_to/__init__.py
  mail_to/__manifest__.py
  mail_to/doc/changelog.rst
  mail_to/i18n/mail_to.pot
  mail_to/models/__init__.py
  mail_to/models/mail_message.py
  mail_to/static/src/js/mail_to.js
  mail_to/static/src/js/test_mail_to.js
  mail_to/static/src/xml/recipient.xml
  mail_to/templates.xml
  mail_to/tests/__init__.py
  mail_to/tests/test_default.py
Labels: 11.0

#75 [bt#8050] Fix
  mail_base/static/lib/base.js
Labels: 11.0-xp

#76 Syncing from upstream it-projects-llc/mail-addons (11.0)
  mail_base/__manifest__.py
  mail_base/doc/changelog.rst
  mail_base/static/lib/base.js
Labels: 11.0
